description: "Create Order POST with scenario"
request:
  method: POST
  path: /order/create/
  body: '{"email": "alma@alma.com", "product": "choco-cookies", "quantity" : 3}'
response:
  headers:
    Content-Type:
      - application/json
  statusCode: 202
  body: '{"status" : "error", "msg" : "unauthorized"}'

control:
  scenario:
    name: orderCreate
    requiredState:
      - not_authorized
  priority: 99
