request:
  method: POST
  path: /user/login/
  body: email=alma@alma.com&password=123
response:
  statusCode: 200
  headers:
    Content-Type:
      - application/json
  body: '{"msg" : "success authorization"}'

control:
  scenario:
    name: orderCreate
    requiredState:
      - not_started
      - not_authorized
    newState: authorized
