request:
  method: POST
  path: /user/logout/

response:
  statusCode: 200
  body: '{"msg" : "success logout"}'
  headers:
    Content-Type:
      - application/json

control:
  scenario:
    name: orderCreate
    requiredState:
      - authorized
    newState: not_authorized
